spring:
  profiles:
    active: receive6001
  application:
    name: receive-server
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
              addresses: rabbitmq-server
              username: studyjava
              password: hello
              virtual-host: /
eureka:
  client:
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可使用“，”分割。
    service-url:
      defaultZone: http://localhost:2001/eureka/,http://localhost:2002/eureka/
  instance:
    #自定义主机映射名称
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #表示将自己的IP注册到Eureka Server
    prefer-ip-address: true
    #hostname: ${spring.cloud.client.ip-address}
---
spring:
  profiles: receive6001
server:
  port: 6001
eureka:
  instance:
    #Eureka Server的实例名称,注意：集群环境不能有一样的名称
    hostname: receive6001
---
spring:
  profiles: receive6002
server:
  port: 6002
eureka:
  instance:
    #Eureka Server的实例名称,注意：集群环境不能有一样的名称
    hostname: receive6002


